import React from "react";
import Box from "@mui/material/Box";
import Typography from "@mui/material/Typography";
import Styles from "./CategoriesListing.module.sass";
import Layout from "../../components/Layout";
import CollectionCard from "../../components/CollectionCard";
import { collectionCardData } from "../../config";
import { useTheme } from "@mui/material/styles";

const CategoriesListing = () => {
  const theme = useTheme();
  return (
    <>
      <Layout>
        <Box className={Styles.categoriesListingContainerWrapper}>
          <Box className={Styles.categoriesListingContainer}>
            <Box className={Styles.categoriesBannerAndInfoContainer}>
              <Box className={Styles.categoriesBannerContainer}></Box>
              <Box className={Styles.categoriesInfoContainer}>
                <Box className={Styles.headingContainer}>
                  <Typography sx={{ color: "text.primary" }}>
                    Explore Art
                  </Typography>
                </Box>
                <Box
                  className={Styles.descriptionContainer}
                  sx={{ color: "text.primary" }}
                >
                  <Typography>
                    Anmutig Studio was launched as a collection of unique NFTs
                    generated by algorithm on the ETH blockchain in oct 2021.
                  </Typography>
                </Box>
              </Box>
            </Box>
            <Box className={Styles.nftCategoriesWiseContainerWrapper}>
              <Box className={Styles.headingContainer}>
                <Typography sx={{ color: "background.fontClr" }}>
                  Trending collections in Art
                </Typography>
              </Box>
              <Box className={Styles.nftCategoriesWiseContainer}>
                {collectionCardData &&
                  collectionCardData.map((v, i) => {
                    return (
                      <CollectionCard
                        key={i}
                        avatarImage={v?.avatarImage}
                        heading={v?.heading}
                        description={v?.description}
                        coverImage={v?.coverImage}
                      />
                    );
                  })}
              </Box>
            </Box>
          </Box>
        </Box>
      </Layout>
    </>
  );
};

export default CategoriesListing;
